global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'FiapCadContato'
    static_configs:
      - targets: ['localhost:7079']
    scheme: https  # to use https instead of http for scraping
    tls_config:
      insecure_skip_verify: true  # This is the key

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']